FROM golang:1.12-alpine AS builder

WORKDIR /build

ADD go.mod .
COPY ./config /config

COPY . .

RUN apk update && apk add git
RUN go build -o ./app ./cmd/main.go

FROM alpine

WORKDIR /build

COPY --from=builder /build/app /build/app
COPY --from=builder build/config /build/config


CMD ["./app"]
