env: "test"

db: "mongo"

server: "grpc"

pgSQL: 
  port: "5432"
  host: "0.0.0.0"
  user: "pgSQL"
  password: "admin"
  DBName: "article"
  SSLMode: "disable"  

redis:
#local
  url: "redis://0.0.0.0:6379"
#deploy 
# url: "rediss://red-cksmfl1f3gac73cm1mdg:1MXMF0Ix6sV8YLm08xXgwvekjJv5afEL@oregon-redis.render.com:6379"
  DB: 0

httpServer:
  port: "8080"
  host: "0.0.0.0"
  readTimeout: 10s
  writeTimeout: 10s

grpc:
  port: "44044"
  timeout: 10s

mongo:
  port: "27017"
  host: "0.0.0.0"
  user: "user"
  password: "user"

