env: "test"
db: "redis"

mysql: 
  port: "5432"
  host: "0.0.0.0"
  user: "user"
  password: "admin"
  

httpServer:
  port: "8080"
  host: "0.0.0.0"
  readTimeout: 10s
  writeTimeout: 10s


redis: 
  port: "6379"
  host: "0.0.0.0"
  password: ""  
  DB: 0